export interface Student {
    id?: number;  // Make the id field optional since it will be generated by the backend
    name: string;
    branch: string;
    year: string;
    cgpa: 0,
    image: string;
    company_name: string;
    employee_type: string;
    linkedin: string;
    github: string;
    user_id: number;
    resume?: string;  // Optional field for the resume URL
    backlogs?: number;
}
